// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laihopquang876.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211010024638_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Laihopquang876.Models.LHQ0876", b =>
                {
                    b.Property<string>("LHQid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LHQGendeR")
                        .HasColumnType("TEXT");

                    b.Property<string>("LHQName")
                        .HasColumnType("TEXT");

                    b.HasKey("LHQid");

                    b.ToTable("LHQ0876");
                });
#pragma warning restore 612, 618
        }
    }
}
